name: dict_appdator
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  build_runner: ^2.3.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  # State Managment
  flutter_mobx: ^2.0.6+4
  mobx: ^2.1.1
  mobx_codegen: ^2.0.7+3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  